/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Module {
  'id' : bigint,
  'name' : string,
  'orderIndex' : bigint,
}
export interface Question {
  'id' : bigint,
  'moduleId' : bigint,
  'explanation' : string,
  'createdAt' : bigint,
  'questionText' : string,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface Quote { 'id' : bigint, 'text' : string, 'author' : string }
export interface _SERVICE {
  'addModule' : ActorMethod<[bigint, string, bigint], undefined>,
  'addQuestion' : ActorMethod<
    [bigint, bigint, string, Array<string>, bigint, string, bigint],
    undefined
  >,
  'addQuote' : ActorMethod<[bigint, string, string], undefined>,
  'getModules' : ActorMethod<[], Array<Module>>,
  'getQuestionsByModule' : ActorMethod<[bigint], Array<Question>>,
  'getQuotes' : ActorMethod<[], Array<Quote>>,
  'isAdminPasswordCorrect' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];