/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Module = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'orderIndex' : IDL.Nat,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'moduleId' : IDL.Nat,
  'explanation' : IDL.Text,
  'createdAt' : IDL.Int,
  'questionText' : IDL.Text,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  'addModule' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'addQuestion' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'addQuote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'deleteModule' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
  'getQuestionsByModule' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'isAdminPasswordCorrect' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Module = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'orderIndex' : IDL.Nat,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'moduleId' : IDL.Nat,
    'explanation' : IDL.Text,
    'createdAt' : IDL.Int,
    'questionText' : IDL.Text,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    'addModule' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'addQuestion' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'addQuote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'deleteModule' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
    'getQuestionsByModule' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'isAdminPasswordCorrect' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };
